name: "infraWorkflow"
on:
  push:
  workflow_dispatch: {}

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_INFRA }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_INFRA }}
      TF_VAR_deployment_branch: ${{secrets.DEPLOYMENT_BRANCH}}
      TF_VAR_game_server_name_image: ${{secrets.GAME_SERVER_NAME_IMAGE}}
      TF_VAR_proxy_name_image: ${{secrets.PROXY_NAME_IMAGE}}
      TF_VAR_hosted_zone_name: ${{secrets.HOSTED_ZONE_NAME}}
      TF_VAR_token_github: ${{secrets.TOKEN_GITHUB}}

    steps:
      - run: 'echo "ENV: ${{ github.ref_name }}"'
      - name: Checkout code
        uses: actions/checkout@v4
      - run: terraform init -backend-config="access_key=${{ secrets.ACCESS_KEY_STATE }}" -backend-config="secret_key=${{ secrets.SECRET_ACCESS_KEY_STATE }}" -backend-config="bucket=${{ secrets.BUCKET_NAME_STATE }}" -backend-config="key=${{ secrets.KEY_STATE }}" -backend-config="region=eu-west-3"
      - run: terraform apply -auto-approve
