name: "infraWorkflow"
on:
  push:
  workflow_dispatch: {}

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_INFRA }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_INFRA }}
      TF_VAR_deployment_branch: ${{secrets.DEPLOYMENT_BRANCH}}
      TF_VAR_admin_mail: ${{secrets.ADMIN_MAIL}}
      TF_VAR_send_mail: ${{secrets.SEND_MAIL}}
      TF_VAR_game_server_name_image: ${{secrets.GAME_SERVER_NAME_IMAGE}}
      TF_VAR_proxy_name_image: ${{secrets.PROXY_NAME_IMAGE}}
      TF_VAR_hosted_zone_name: ${{secrets.HOSTED_ZONE_NAME}}
      TF_VAR_token_github: ${{secrets.TOKEN_GITHUB}}
      TF_VAR_app_name: ${{secrets.APP_NAME}}
      TF_VAR_website_name: ${{secrets.WEBSITE_NAME}}
      TF_VAR_cloudfront_function_arn: ${{secrets.CLOUDFRONT_FUNCTION_ARN}}

      TF_VAR_subdomain_auth: ${{secrets.SUBDOMAIN_AUTH}}
      TF_VAR_admin_cognito_username: ${{secrets.ADMIN_COGNITO_USERNAME}}
      TF_VAR_admin_cognito_password: ${{secrets.ADMIN_COGNITO_PASSWORD}}
      TF_VAR_classic_cognito_username: ${{secrets.CLASSIC_COGNITO_USERNAME}}
      TF_VAR_classic_cognito_password: ${{secrets.CLASSIC_COGNITO_PASSWORD}}
      TF_VAR_default_cognito_mail: ${{secrets.DEFAULT_COGNITO_MAIL}}

    steps:
      - run: 'echo "ENV: ${{ github.ref_name }}"'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          tag: ${{ github.ref_name }}_${{ github.run_number }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      
      - run: terraform init -backend-config="access_key=${{ secrets.ACCESS_KEY_STATE }}" -backend-config="secret_key=${{ secrets.SECRET_ACCESS_KEY_STATE }}" -backend-config="bucket=${{ secrets.BUCKET_NAME_STATE }}" -backend-config="key=${{ secrets.KEY_STATE }}" -backend-config="region=eu-west-3"
      - run: terraform apply -auto-approve
